DROP TABLE IF EXISTS STOCK_PRICES;
DROP TABLE IF EXISTS TBL_EMPLOYEES;

CREATE TABLE STOCK_PRICES (
  wkn INT PRIMARY KEY,
  price DOUBLE NOT NULL
);

CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);